version: '3.9'

services:
  php:
    container_name: ${DOCKER_PROJECT_NAME}_php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      # if you use supervisor
      #- ./docker/php/supervisor/messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf
    build: ./docker/php
    depends_on:
      - mysql

  nginx:
    container_name: ${DOCKER_PROJECT_NAME}_nginx
    image: nginx:1.19
    restart: unless-stopped
    volumes:
      - ./docker/nginx/logs:/var/log/nginx
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
    ports:
      - 127.0.0.1:${DOCKER_NGINX_PORT}:80

  mysql:
    image: mariadb:10.5.2
    container_name: ${DOCKER_PROJECT_NAME}_mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_PROJECT_NAME}
    volumes:
      # - ./sql:/sql
      - ./docker/mysql/db:/var/lib/mysql
    ports:
      - 127.0.0.1:${DOCKER_DATABASE_PORT}:3306

#  postgres:
#    image: postgres:14
#    restart: unless-stopped
#    container_name: ${DOCKER_PROJECT_NAME}_postgres
#    ports:
#      - 127.0.0.1:${DOCKER_DATABASE_PORT}:5432
#    volumes:
#      - ./docker/postgres/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
#      - POSTGRES_USER=${DATABASE_USER}
#      - POSTGRES_DB=${DOCKER_PROJECT_NAME}

#    redis:
#        image: redis:6.0.10-alpine
#        restart: unless-stopped
#        container_name: ${DOCKER_PROJECT_NAME}_redis
