controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

not_found:
    path: /
    controller: App\Controller\ErrorController::notFound
    requirements:
        catchall: '.*'
